#!/usr/bin/env node

var CONF  = require('./package.json')
var spawn = require('child_process').spawn
var path  = require('path')
var version = CONF.version.split('.').slice(0, 2).join('.')
var plugin = path.join(__dirname, 'plugin', CONF.name, version, 'hooks')

function info (i) { process.stdout.write('\033[1;32m' + i + '\033[0m\n') }
function run (opt, msg) {
    var installation = spawn('ti', ['config', 'paths.hooks', opt, plugin])
    installation.stderr.pipe(process.stderr)
    installation.on("exit", function (code) {
        if (code === 0) {
            info(CONF.name + ' v' + CONF.version + ' successfully ' + msg + '.')
        }
        process.exit(code)
    })
}

run.apply(null, process.argv[2] === 'install' ? ['-a', 'installed'] : ['-r', 'uninstalled'])
